/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#121c2a",
        "on-surface-variant": "#3c4a46",
        "on-background": "#121c2a",
        "on-tertiary-fixed": "#261a00",
        outline: "#6b7a76",
        "on-secondary-fixed": "#001c39",
        surface: "#f8f9ff",
        "secondary-container": "#64a8fe",
        "primary-fixed": "#A9C2F5",
        "primary-container": "#A9C2F5",
        "surface-variant": "#d9e3f6",
        "on-primary-fixed": "#142B5C",
        "tertiary-container": "#efb515",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#634900",
        primary: "#1D3E82",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d4e3ff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dee9fc",
        "inverse-primary": "#A9C2F5",
        "on-primary-container": "#142B5C",
        "inverse-surface": "#27313f",
        "tertiary-fixed": "#ffdf9f",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#f9bd22",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#E08E10",
        "surface-container": "#e6eeff",
        error: "#ba1a1a",
        "surface-dim": "#d0dbed",
        "surface-tint": "#1D3E82",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#bacac5",
        background: "#F4F6FA",
        "secondary-fixed-dim": "#a4c9ff",
        "primary-fixed-dim": "#8FB3F0",
        "surface-container-highest": "#d9e3f6",
        "on-secondary-fixed-variant": "#004883",
        "on-secondary-container": "#003c70",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        secondary: "#0060ac",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-primary-fixed-variant": "#142B5C",
        navy: "#1D3E82",
        "navy-dark": "#142B5C",
        "navy-darkest": "#0F2148",
        "navy-mid": "#2C56A8",
        accent: "#F6A623",
        "accent-dark": "#E08E10",
        "text-muted": "#5C6B8A",
        "text-faint": "#8993AC",
        "chip-bg": "#EDEFF6",
        "chip-bg-alt": "#E8ECF7",
        "border-soft": "#DCE2EE",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "20px",
        "section-padding": "32px",
        gutter: "16px",
        "stack-lg": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        button: ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-xl": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "22px",
          { lineHeight: "28px", fontWeight: "700" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
