import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import AdminUsersPage from "../src/pages/admin/AdminUsersPage";
import AdminUserDetailPage from "../src/pages/admin/AdminUserDetailPage";
import LockUserDialog from "../src/components/admin/users/LockUserDialog";
import AssignRoleDialog from "../src/components/admin/roles/AssignRoleDialog";
const mocks = vi.hoisted(() => ({ auth: { user: { id: "admin", permissions: [] } }, users: { getUsers: vi.fn(), getFilterOptions: vi.fn(), getUser: vi.fn(), getUserPayments: vi.fn(), getUserTrips: vi.fn(), lockUser: vi.fn(), unlockUser: vi.fn() }, roles: { getRoles: vi.fn(), getPermissions: vi.fn(), assignUserRole: vi.fn() } }));
vi.mock("../src/context/AuthContext", () => ({ useAuth: () => mocks.auth }));
vi.mock("../src/services/adminUserService", () => ({ adminUserService: mocks.users }));
vi.mock("../src/services/adminRoleService", () => ({ adminRoleService: mocks.roles }));
vi.mock("../src/components/admin/transactions", () => ({ TransactionDetailDrawer: ({ isOpen, transactionId }) => isOpen ? <p>Transaction {transactionId}</p> : null }));
const user = { id: "u", fullName: "Local User", email: "user@example.test", status: "Active", role: { id: "r", name: "User" }, plan: { name: "Free" }, createdAt: "2026-10-01T00:00:00Z", canLock: false, canUnlock: false };
const detail = { ...user, hasPassword: true, loginProviders: ["Google"], stats: { tripCount: 8, finalizedTripCount: 3, deletedTripCount: 2, totalPaid: 123000, paidOrderCount: 5, unusedSingleItineraryCount: 2 }, subscription: { plan: "FREE", usage: { generateUsed: 3, generateLimit: 1 }, savedTrips: { used: 1, limit: 1 } } };
const payment = { id: "pay", orderCode: 93, amount: 19000, status: "Paid", createdAt: "2026-10-01T00:00:00Z", paidAt: "2026-10-02T00:00:00Z", plan: { code: "TRIP_PASS", name: "Trip Pass" } };
const trip = { id: "trip", plannedDate: "2026-10-03", startTime: "09:00:00", durationHours: 3, status: "Finalized", travelMode: "Walking", itemCount: 4, estimatedBudget: 100000, budgetMax: 200000, createdAt: "2026-10-01T00:00:00Z", finalizedAt: "2026-10-02T00:00:00Z" };
const paged = (items, page = 1) => ({ items, page, totalPages: 2, totalCount: 21 });
const table = () => within(screen.getByRole("table"));
const mount = element => render(<MemoryRouter>{element}</MemoryRouter>);
async function list(rows = [user]) { mocks.users.getUsers.mockImplementation(async q => paged(rows, q.page)); mount(<AdminUsersPage />); await table().findByText(rows[0]?.fullName ?? "Chưa có người dùng"); }
async function profile(value = detail) { mocks.users.getUser.mockResolvedValue(value); render(<MemoryRouter initialEntries={["/admin/users/u"]}><Routes><Route path="/admin/users/:userId" element={<AdminUserDetailPage />} /></Routes></MemoryRouter>); await screen.findByRole("heading", { name: value.fullName }); await table().findByText("19.000đ"); }
beforeEach(() => {
  vi.clearAllMocks(); mocks.auth.user = { id: "admin", permissions: [] };
  mocks.users.getUsers.mockImplementation(async q => paged([user], q.page));
  mocks.users.getFilterOptions.mockResolvedValue({ roles: [{ id: "r", name: "User" }], plans: [{ code: "FREE", name: "Free", isActive: true }] });
  mocks.users.getUserPayments.mockImplementation(async (_, q) => paged([payment], q.page));
  mocks.users.getUserTrips.mockImplementation(async (_, q) => paged([trip], q.page));
  mocks.users.lockUser.mockResolvedValue({}); mocks.users.unlockUser.mockResolvedValue({});
  mocks.roles.getRoles.mockResolvedValue([{ id: "r", name: "User", permissions: [] }, { id: "m", name: "Manager", permissions: ["ManageUsers"] }]);
  mocks.roles.getPermissions.mockResolvedValue([{ code: "ManageUsers", name: "Quản lý người dùng" }]);
});
afterEach(() => vi.useRealTimers());
describe("A6 Users query and server action authority", () => {
  it("preserves initial server query and one shared desktop/mobile fetch", async () => { await list(); expect(mocks.users.getUsers).toHaveBeenCalledTimes(1); expect(mocks.users.getUsers.mock.lastCall[0]).toEqual({ page: 1, pageSize: 20, sortBy: "createdAt", sortDirection: "desc", search: "", status: "", roleId: "", plan: "" }); expect(within(screen.getByLabelText("Danh sách người dùng trên di động")).getByText("Local User")).toBeInTheDocument(); });
  it("search waits 350ms and resets page", async () => { vi.useFakeTimers(); mount(<AdminUsersPage />); await act(async () => {}); fireEvent.click(screen.getByRole("button", { name: "Sau" })); await act(async () => {}); mocks.users.getUsers.mockClear(); fireEvent.change(screen.getByRole("searchbox"), { target: { value: "Minh" } }); await act(async () => vi.advanceTimersByTime(349)); expect(mocks.users.getUsers).not.toHaveBeenCalled(); await act(async () => vi.advanceTimersByTime(1)); expect(mocks.users.getUsers.mock.lastCall[0]).toMatchObject({ search: "Minh", page: 1 }); });
  it.each([["Lọc theo trạng thái", "Locked", "status"], ["Lọc theo role", "r", "roleId"], ["Lọc theo gói", "FREE", "plan"]])("%s preserves query and page reset", async (label, value, key) => { await list(); await screen.findByRole("combobox", { name: label }); fireEvent.click(screen.getByRole("button", { name: "Sau" })); await waitFor(() => expect(mocks.users.getUsers.mock.lastCall[0].page).toBe(2)); fireEvent.change(screen.getByLabelText(label), { target: { value } }); await waitFor(() => expect(mocks.users.getUsers.mock.lastCall[0]).toMatchObject({ [key]: value, page: 1 })); });
  it("preserves sorting, pagination and reset", async () => { await list(); fireEvent.click(screen.getByRole("button", { name: "Sắp xếp theo Người dùng" })); await waitFor(() => expect(mocks.users.getUsers.mock.lastCall[0]).toMatchObject({ sortBy: "fullName", sortDirection: "asc" })); fireEvent.change(screen.getByLabelText("Lọc theo trạng thái"), { target: { value: "Locked" } }); fireEvent.click(screen.getByRole("button", { name: "Xóa lọc" })); await waitFor(() => expect(mocks.users.getUsers.mock.lastCall[0]).toMatchObject({ status: "", sortBy: "fullName", page: 1 })); });
  it("options failure does not block users", async () => { mocks.users.getFilterOptions.mockRejectedValue(new Error("options unavailable")); await list(); expect(table().getByText("Local User")).toBeInTheDocument(); expect(screen.queryByRole("alert")).not.toBeInTheDocument(); });
  it.each([["Active", false, false], ["Locked", true, false], ["Active", false, true], ["Locked", true, true]])("status %s never reconstructs lock %s/unlock %s", async (status, canLock, canUnlock) => { await list([{ ...user, status, canLock, canUnlock }]); expect(table().queryByRole("button", { name: /Khoá$/ }) !== null).toBe(canLock); expect(table().queryByRole("button", { name: /Mở khoá$/ }) !== null).toBe(canUnlock); });
  it("mobile view link and server-approved lock are keyboard reachable", async () => { await list([{ ...user, canLock: true }]); const mobile = within(screen.getByLabelText("Danh sách người dùng trên di động")); expect(mobile.getByRole("link", { name: /Xem/ })).toHaveAttribute("href", "/admin/users/u"); const button = mobile.getByRole("button", { name: /Khoá/ }); button.focus(); expect(button).toHaveFocus(); });
  it("error is not an empty success and retry preserves query", async () => { mocks.users.getUsers.mockRejectedValue(new Error("users unavailable")); mount(<AdminUsersPage />); expect(await screen.findByRole("alert")).toHaveTextContent("users unavailable"); expect(screen.queryByText("Chưa có người dùng")).not.toBeInTheDocument(); mocks.users.getUsers.mockResolvedValue(paged([user])); fireEvent.click(screen.getByRole("button", { name: "Thử lại" })); await screen.findByRole("table"); await table().findByText("Local User"); });
});
describe("A6 Lock/Unlock dialog", () => {
  it("lock requires trimmed reason and exact callback", async () => { const done = vi.fn(); render(<LockUserDialog user={user} mode="lock" onClose={vi.fn()} onDone={done} />); expect(screen.getByRole("button", { name: "Khoá tài khoản" })).toBeDisabled(); fireEvent.change(screen.getByLabelText("Lý do khoá *"), { target: { value: "  reason  " } }); fireEvent.click(screen.getByRole("button", { name: "Khoá tài khoản" })); await waitFor(() => expect(mocks.users.lockUser).toHaveBeenCalledWith("u", "reason")); expect(done).toHaveBeenCalledWith({}); });
  it("max500 prevents submission", () => { render(<LockUserDialog user={user} mode="lock" onClose={vi.fn()} onDone={vi.fn()} />); fireEvent.change(screen.getByLabelText("Lý do khoá *"), { target: { value: "a".repeat(501) } }); expect(screen.getByRole("button", { name: "Khoá tài khoản" })).toBeDisabled(); expect(screen.getByRole("alert")).toHaveTextContent("500"); });
  it("unlock sends no reason", async () => { render(<LockUserDialog user={user} mode="unlock" onClose={vi.fn()} onDone={vi.fn()} />); expect(screen.queryByRole("textbox")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Mở khoá" })); await waitFor(() => expect(mocks.users.unlockUser).toHaveBeenCalledWith("u")); });
  it("in-flight submission blocks duplicate and dismissal", async () => { mocks.users.lockUser.mockReturnValue(new Promise(() => {})); const close = vi.fn(); render(<LockUserDialog user={user} mode="lock" onClose={close} onDone={vi.fn()} />); fireEvent.change(screen.getByRole("textbox"), { target: { value: "reason" } }); fireEvent.click(screen.getByRole("button", { name: "Khoá tài khoản" })); expect(screen.getByRole("button", { name: "Đang xử lý..." })).toBeDisabled(); fireEvent.keyDown(document, { key: "Escape" }); expect(close).not.toHaveBeenCalled(); expect(mocks.users.lockUser).toHaveBeenCalledTimes(1); });
  it.each(["cannot_lock_self", "cannot_manage_role_manager", "last_role_manager", "user_not_found"])("preserves %s error", async code => { mocks.users.unlockUser.mockRejectedValue({ code }); render(<LockUserDialog user={user} mode="unlock" onClose={vi.fn()} onDone={vi.fn()} />); fireEvent.click(screen.getByRole("button", { name: "Mở khoá" })); expect(await screen.findByRole("alert")).not.toBeEmptyDOMElement(); });
  it("focus traps and restores after cancel", async () => {
    const trigger = document.createElement("button"); document.body.append(trigger); trigger.focus(); const result = render(<LockUserDialog user={user} mode="lock" onClose={vi.fn()} onDone={vi.fn()} />); expect(screen.getByRole("textbox")).toHaveFocus(); fireEvent.keyDown(screen.getByRole("textbox"), { key: "Tab", shiftKey: true }); expect(screen.getByRole("button", { name: "Hủy" })).toHaveFocus(); result.unmount(); expect(trigger).toHaveFocus(); trigger.remove();
  });
});
describe("A6 User detail preservation", () => {
  it("renders server account/subscription/stats without recomputation", async () => { await profile(); expect(screen.getByText("123.000đ")).toBeInTheDocument(); expect(screen.getByText("3/1")).toBeInTheDocument(); expect(screen.getByText("Email & mật khẩu, Google")).toBeInTheDocument(); expect(screen.getByText("3 đã chốt · 2 đã xoá")).toBeInTheDocument(); });
  it("user_not_found preserves not-found route", async () => { mocks.users.getUser.mockRejectedValue({ code: "user_not_found" }); render(<MemoryRouter initialEntries={["/admin/users/u"]}><Routes><Route path="/admin/users/:userId" element={<AdminUserDetailPage />} /></Routes></MemoryRouter>); await screen.findByText("Không tìm thấy người dùng"); expect(screen.getByRole("link", { name: /Danh sách người dùng/ })).toHaveAttribute("href", "/admin/users"); });
  it.each([[[], "u", false], [["ManageRoles"], "u", true], [["ManageRoles"], "admin", false]])("assignment requires permission and never allows self", async (permissions, id, allowed) => { mocks.auth.user.permissions = permissions; await profile({ ...detail, id }); expect(screen.queryByRole("button", { name: "Đổi role" }) !== null).toBe(allowed); });
  it.each([false, true])("ViewRevenue gates transaction details: %s", async allowed => { mocks.auth.user.permissions = allowed ? ["ViewRevenue"] : []; await profile(); expect(table().queryByRole("button", { name: /Xem chi tiết đơn hàng/ }) !== null).toBe(allowed); if (allowed) { fireEvent.click(table().getByRole("button", { name: /Xem chi tiết đơn hàng/ })); expect(screen.getByText("Transaction pay")).toBeInTheDocument(); } });
  it("payments keep server paging/sort and same mobile rows", async () => { await profile(); expect(within(screen.getByLabelText("Lịch sử thanh toán trên di động")).getByText("19.000đ")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Sắp xếp theo Thực trả" })); await waitFor(() => expect(mocks.users.getUserPayments.mock.lastCall).toEqual(["u", { page: 1, pageSize: 10, sortBy: "amount", sortDirection: "desc" }])); fireEvent.click(screen.getByRole("button", { name: "Sau" })); await waitFor(() => expect(mocks.users.getUserPayments.mock.lastCall[1].page).toBe(2)); });
  it("trips preserve filters, paging/sort and shared rows", async () => { await profile(); fireEvent.click(screen.getByRole("tab", { name: "Lịch sử chuyến đi" })); await table().findByText("3 giờ · Đi bộ"); expect(mocks.users.getUserTrips).toHaveBeenCalledTimes(1); expect(within(screen.getByLabelText("Lịch sử chuyến đi trên di động")).getByText("3 giờ · Đi bộ")).toBeInTheDocument(); fireEvent.change(screen.getByLabelText("Lọc chuyến đi theo trạng thái"), { target: { value: "Finalized" } }); fireEvent.click(screen.getByLabelText("Hiện cả chuyến đã xoá")); await waitFor(() => expect(mocks.users.getUserTrips.mock.lastCall[1]).toMatchObject({ status: "Finalized", includeDeleted: true, page: 1, pageSize: 10 })); fireEvent.click(screen.getByRole("button", { name: "Sắp xếp theo Chốt lúc" })); await waitFor(() => expect(mocks.users.getUserTrips.mock.lastCall[1]).toMatchObject({ sortBy: "finalizedAt", sortDirection: "desc" })); expect(screen.getByRole("tabpanel")).toHaveAttribute("aria-labelledby", "user-history-trips"); });
  it("detail canLock is not inferred from locked status", async () => { await profile({ ...detail, status: "Locked", canLock: false, canUnlock: false }); expect(screen.queryByRole("button", { name: /Khoá tài khoản|Mở khoá/ })).not.toBeInTheDocument(); });
  it("refresh error retains detail then user_not_found clears it", async () => { await profile({ ...detail, canUnlock: true }); mocks.users.getUser.mockRejectedValueOnce(new Error("refresh failed")).mockRejectedValueOnce({ code: "user_not_found" }); fireEvent.click(screen.getByRole("button", { name: /Mở khoá/ })); fireEvent.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Mở khoá" })); await screen.findByText("refresh failed"); expect(screen.getByRole("heading", { name: "Local User" })).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Thử lại" })); await screen.findByText("Không tìm thấy người dùng"); expect(screen.queryByRole("heading", { name: "Local User" })).not.toBeInTheDocument(); });
});
describe("A6 Assign role dialog", () => {
  it("keeps current selection disabled and sends exact roleId", async () => { mocks.roles.assignUserRole.mockResolvedValue({ roleName: "Manager" }); const done = vi.fn(); render(<AssignRoleDialog user={user} onClose={vi.fn()} onAssigned={done} />); await screen.findByLabelText("Role mới"); expect(screen.getByRole("button", { name: "Đổi role" })).toBeDisabled(); fireEvent.change(screen.getByLabelText("Role mới"), { target: { value: "m" } }); expect(screen.getByText("Quyền: Quản lý người dùng.")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Đổi role" })); await waitFor(() => expect(mocks.roles.assignUserRole).toHaveBeenCalledWith("u", "m")); expect(done).toHaveBeenCalledWith({ roleName: "Manager" }); });
  it("self-change server error remains visible", async () => { mocks.roles.assignUserRole.mockRejectedValue({ code: "cannot_change_own_role" }); render(<AssignRoleDialog user={user} onClose={vi.fn()} onAssigned={vi.fn()} />); await screen.findByLabelText("Role mới"); fireEvent.change(screen.getByLabelText("Role mới"), { target: { value: "m" } }); fireEvent.click(screen.getByRole("button", { name: "Đổi role" })); expect(await screen.findByRole("alert")).toHaveTextContent("Không thể tự đổi role"); });
  it("focus trap/Escape and restoration remain safe", async () => { const trigger = document.createElement("button"); document.body.append(trigger); trigger.focus(); const close = vi.fn(); const result = render(<AssignRoleDialog user={user} onClose={close} onAssigned={vi.fn()} />); await screen.findByLabelText("Role mới"); screen.getByRole("button", { name: "Hủy" }).focus(); fireEvent.keyDown(document, { key: "Tab" }); expect(screen.getByLabelText("Role mới")).toHaveFocus(); fireEvent.keyDown(document, { key: "Escape" }); expect(close).toHaveBeenCalledTimes(1); result.unmount(); expect(trigger).toHaveFocus(); trigger.remove(); });
});
