import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import AdminRolesPage from "../src/pages/admin/AdminRolesPage";
import RoleFormDialog from "../src/components/admin/roles/RoleFormDialog";
const mocks = vi.hoisted(() => ({ roles: { getRoles: vi.fn(), getPermissions: vi.fn(), createRole: vi.fn(), updateRole: vi.fn(), deleteRole: vi.fn() }, refreshProfile: vi.fn() }));
vi.mock("../src/services/adminRoleService", () => ({ adminRoleService: mocks.roles }));
vi.mock("../src/context/AuthContext", () => ({ useAuth: () => ({ refreshProfile: mocks.refreshProfile }) }));
const permissions = [{ code: "ManageUsers", name: "Quản lý người dùng", description: "Tài khoản" }, { code: "ManageRoles", name: "Quản lý phân quyền", description: "Phân quyền" }];
const role = { id: "custom", name: "Support", description: "Help desk", isSystem: false, userCount: 0, permissions: ["ManageUsers"] };
const table = () => within(screen.getByRole("table"));
beforeEach(() => { vi.clearAllMocks(); mocks.roles.getRoles.mockResolvedValue([role]); mocks.roles.getPermissions.mockResolvedValue(permissions); mocks.roles.createRole.mockResolvedValue(role); mocks.roles.updateRole.mockResolvedValue(role); mocks.roles.deleteRole.mockResolvedValue({}); mocks.refreshProfile.mockResolvedValue({}); });
async function list(rows = [role]) { mocks.roles.getRoles.mockResolvedValue(rows); render(<AdminRolesPage />); await table().findByText(rows[0].name); }
function form(value = null, done = vi.fn()) { render(<RoleFormDialog role={value} permissions={permissions} onClose={vi.fn()} onSaved={done} />); return done; }
describe("A6 Roles contracts and governance safety", () => {
  it("same role collection and server permissions feed desktop/mobile", async () => { await list(); expect(mocks.roles.getRoles).toHaveBeenCalledTimes(1); expect(table().getByText("Quản lý người dùng")).toBeInTheDocument(); expect(within(screen.getByLabelText("Danh sách role trên di động")).getByText("Support")).toBeInTheDocument(); });
  it("system role remains immutable", async () => { await list([{ ...role, isSystem: true }]); expect(table().getByText("Hệ thống")).toBeInTheDocument(); expect(table().queryByRole("button")).not.toBeInTheDocument(); expect(table().getByText("Không sửa được")).toBeInTheDocument(); });
  it("role with users cannot be deleted", async () => { await list([{ ...role, userCount: 2 }]); expect(table().getByRole("button", { name: /Xoá/ })).toBeDisabled(); expect(table().getByRole("button", { name: /Xoá/ })).toHaveAttribute("title", "Role đang có người dùng, hãy chuyển họ sang role khác trước"); });
  it("deletion confirmation cancels without mutation", async () => { await list(); fireEvent.click(table().getByRole("button", { name: /Xoá/ })); fireEvent.click(screen.getByRole("button", { name: "Hủy" })); expect(mocks.roles.deleteRole).not.toHaveBeenCalled(); });
  it("role_in_use deletion error remains visible", async () => { mocks.roles.deleteRole.mockRejectedValue({ code: "role_in_use" }); await list(); fireEvent.click(table().getByRole("button", { name: /Xoá/ })); fireEvent.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Xoá role" })); await screen.findByText("Role đang có người dùng, hãy chuyển họ sang role khác trước."); });
  it("create sends trimmed name/nullable description/exact selected permission codes", async () => { const done = form(); fireEvent.change(screen.getByLabelText("Tên role *"), { target: { value: "  Support  " } }); fireEvent.click(screen.getByRole("checkbox", { name: /Quản lý phân quyền/ })); fireEvent.click(screen.getByRole("button", { name: "Tạo role" })); await waitFor(() => expect(mocks.roles.createRole).toHaveBeenCalledWith({ name: "Support", description: null, permissions: ["ManageRoles"] })); expect(done).toHaveBeenCalledWith(role, false); });
  it("edit preserves original selection and payload ordering", async () => { form(role); expect(screen.getByRole("checkbox", { name: /Quản lý người dùng/ })).toBeChecked(); fireEvent.click(screen.getByRole("checkbox", { name: /Quản lý phân quyền/ })); fireEvent.click(screen.getByRole("button", { name: "Lưu thay đổi" })); await waitFor(() => expect(mocks.roles.updateRole).toHaveBeenCalledWith("custom", { name: "Support", description: "Help desk", permissions: ["ManageUsers", "ManageRoles"] })); });
  it.each(["role_name_exists", "system_role_locked", "last_role_manager", "cannot_remove_own_role_manager", "role_not_found", "invalid_role"])("preserves %s error instead of weakening protection", async code => { mocks.roles.updateRole.mockRejectedValue({ code }); form(role); fireEvent.click(screen.getByRole("button", { name: "Lưu thay đổi" })); expect(await screen.findByRole("alert")).not.toBeEmptyDOMElement(); });
  it("name and description validation preserve limits", () => { form(); fireEvent.change(screen.getByLabelText("Tên role *"), { target: { value: "a".repeat(51) } }); fireEvent.change(screen.getByLabelText("Mô tả"), { target: { value: "b".repeat(201) } }); expect(screen.getByRole("button", { name: "Tạo role" })).toBeDisabled(); expect(screen.getAllByRole("alert")).toHaveLength(2); });
  it("edit refreshes profile, create does not", async () => { await list(); fireEvent.click(table().getByRole("button", { name: /Sửa/ })); fireEvent.click(screen.getByRole("button", { name: "Lưu thay đổi" })); await waitFor(() => expect(mocks.refreshProfile).toHaveBeenCalledTimes(1)); });
  it("save guard blocks double submission and Escape", async () => { mocks.roles.updateRole.mockReturnValue(new Promise(() => {})); form(role); fireEvent.click(screen.getByRole("button", { name: "Lưu thay đổi" })); expect(screen.getByRole("button", { name: "Đang lưu..." })).toBeDisabled(); expect(screen.getByRole("button", { name: "Hủy" })).toBeDisabled(); expect(mocks.roles.updateRole).toHaveBeenCalledTimes(1); });
  it("form focus enters, traps, restores and permission checkboxes are named", () => { const trigger = document.createElement("button"); document.body.append(trigger); trigger.focus(); const result = render(<RoleFormDialog role={null} permissions={permissions} onClose={vi.fn()} onSaved={vi.fn()} />); expect(screen.getByLabelText("Tên role *")).toHaveFocus(); expect(screen.getAllByRole("checkbox")).toHaveLength(2); fireEvent.keyDown(document, { key: "Tab", shiftKey: true }); expect(screen.getByRole("button", { name: "Hủy" })).toHaveFocus(); result.unmount(); expect(trigger).toHaveFocus(); trigger.remove(); });
});
