import { ADMIN_PERMISSIONS as P } from "../../constants";

// Các mục Admin Portal theo design Figma "LocalMate" + quyền BE cần (có 1 trong số đó là vào được).
// Dùng chung cho sidebar, route, breadcrumb, dashboard. `group` là mục giữa của breadcrumb.
export const ADMIN_SECTIONS = [
  {
    path: "stations",
    navLabel: "Ga Metro",
    navGroup: "Dữ liệu Metro",
    label: "Quản lý Ga Metro",
    group: "Dữ liệu Metro",
    icon: "directions_subway",
    permissions: [P.MANAGE_PLACES],
    description: "Xem 14 ga, số địa điểm theo trạng thái, loại và ga thiếu dữ liệu.",
    tone: "bg-sky-50 text-sky-700",
  },
  {
    path: "places",
    navLabel: "Địa điểm",
    navGroup: "Dữ liệu Metro",
    label: "Địa điểm & Tiện ích",
    group: "Dữ liệu Metro",
    icon: "location_on",
    permissions: [P.MANAGE_PLACES],
    description: "Tạo, sửa, duyệt và xác minh địa điểm.",
    tone: "bg-emerald-50 text-emerald-700",
  },
  {
    path: "import",
    navLabel: "Import dữ liệu",
    navGroup: "Dữ liệu Metro",
    label: "Nhập dữ liệu Excel",
    group: "Dữ liệu Metro",
    icon: "upload_file",
    permissions: [P.MANAGE_PLACES],
    description: "Nhập hàng loạt địa điểm từ file CSV/Excel.",
    tone: "bg-teal-50 text-teal-700",
  },
  {
    path: "curated-itineraries",
    navLabel: "Lịch trình mẫu",
    navGroup: "Dữ liệu Metro",
    label: "Lịch trình mẫu",
    group: "Dữ liệu Metro",
    icon: "route",
    permissions: [P.MANAGE_PLACES],
    description: "Tạo, sửa, xoá lịch trình mẫu hiện ở trang Khám phá.",
    tone: "bg-indigo-50 text-indigo-700",
  },
  {
    path: "plans",
    navLabel: "Gói thành viên",
    navGroup: "Kinh doanh",
    label: "Gói thành viên",
    group: "Gói cước & Doanh thu",
    icon: "sell",
    permissions: [P.MANAGE_PLANS],
    description: "Cấu hình gói, giá và lượt tạo lịch trình.",
    tone: "bg-amber-50 text-amber-700",
  },
  {
    path: "transactions",
    navLabel: "Giao dịch",
    navGroup: "Kinh doanh",
    label: "Giao dịch PayOS",
    group: "Gói cước & Doanh thu",
    icon: "payments",
    permissions: [P.VIEW_REVENUE],
    description: "Tra cứu và đối soát giao dịch thanh toán.",
    tone: "bg-orange-50 text-orange-700",
  },
  {
    path: "users",
    navLabel: "Users",
    navGroup: "Người dùng",
    label: "Quản lý Users",
    group: "Người dùng & Phân quyền",
    icon: "group",
    permissions: [P.MANAGE_USERS],
    description: "Xem danh sách, khoá và mở khoá tài khoản.",
    tone: "bg-blue-50 text-blue-700",
  },
  {
    path: "feedback",
    navLabel: "Phản hồi",
    navGroup: "Người dùng",
    label: "Phản hồi & đánh giá",
    group: "Người dùng & Phân quyền",
    icon: "reviews",
    permissions: [P.VIEW_FEEDBACK],
    description: "Xem đánh giá địa điểm, feedback chuyến đi và thống kê.",
    tone: "bg-rose-50 text-rose-700",
  },
  {
    path: "roles",
    navLabel: "Phân quyền",
    navGroup: "Người dùng",
    label: "Phân quyền & Quản trị",
    group: "Người dùng & Phân quyền",
    icon: "admin_panel_settings",
    permissions: [P.MANAGE_ROLES],
    description: "Tạo role, chọn quyền và gán role cho người dùng.",
    tone: "bg-violet-50 text-violet-700",
  },
  {
    path: "settings",
    navLabel: "Cấu hình",
    navGroup: "Hệ thống",
    label: "Cấu hình hệ thống",
    group: "Hệ thống",
    icon: "tune",
    permissions: [P.MANAGE_SETTINGS],
    description: "Chỉnh ngưỡng ga, tốc độ di chuyển, mục tiêu hoà vốn...",
    tone: "bg-slate-100 text-slate-700",
  },
];
